#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

res_dir=$1
pos=$2

rs=(0:1 1:0 9:1 1:1 3:1)
ls=(0.5 0.9)
ps=(uni par)
ds=(0 50 100 150)

for r in "${rs[@]}"; do
  for l in "${ls[@]}"; do
    for p in "${ps[@]}"; do
      for d in "${ds[@]}"; do
        echo $r $l $p $d
        src=$(grep "$r $l $p $d" index_w_2 | head -$pos | tail -1 | cut -d' ' -f5)
        echo $src
        mv $src $res_dir
      done
    done
  done
done

exit 0
