#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

for n in $(cat all_nodes); do
  ssh root@$n "echo 6710887 > /proc/sys/net/core/wmem_default
echo 6710887 > /proc/sys/net/core/wmem_max
echo 6710887 > /proc/sys/net/core/rmem_default
echo 6710887 > /proc/sys/net/core/rmem_max" &
done; wait
