#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

option=${1:--s}

case $option in
  -s) ps -C run-all;;
  -k) pgid=$(ps -C run-all -o pgid= | tr -d ' ')
      [[ -n $pgid ]] && kill -TERM -$pgid && echo run-all killed
      for n in $(cat bench_nodes); do
        ssh root@$n "pid=\$(ps -C beam.smp -o pid= | tr -d ' ') && \
[[ -n \$pid ]] && kill -TERM \$pid && echo basho_bench killed" &
      done; wait
esac 
