#!/bin/bash

in=(-w\|-r ev\|any\|lat locality popularity duration\|rw_ratio)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

option=$1
[[ $2 == lat ]] && tl_mode=lat || tl_mode=any # any for the rest
locality=$3
pop=$4

case $option in
  -w) conf_file=bench-warmup.config
      rw_ratio="0:1"
      dur=$5;;
  -r) conf_file=bench.config
      rw_ratio=$5
      dur=$TEST_DURATION
esac

loc[1]=$(printf "%1.2f" $locality)
loc[2]=$(printf "%1.2f" $(bc <<< "1-$locality"))

case $pop in
  uni) keygen=uniform_int;;
  par) keygen=truncated_pareto_int 
esac

gets=$(echo $rw_ratio | cut -d':' -f1)
upds=$(echo $rw_ratio | cut -d':' -f2)
ops=""
[[ $gets != 0 ]] && ops="{get, $gets}"
[[ $gets != 0 ]] && [[ $upds != 0 ]] && ops=$ops,
[[ $upds != 0 ]] && ops=$ops"{update_existing, $upds}"

clis=$(cat bench_nodes | wc -l)
((clis_dc=clis/2))
  
ips_dc=$(cat ips-1 | wc -l)  # both dcs have the same ip count
((ips_cli=ips_dc/clis_dc))
for dc in {1..2}; do
  for ((c=1, i=1; c<=clis_dc; c++, i+=ips_cli)); do
    ips_str=$(sed -n "$i,$((i+ips_cli-1)) s/\(.*\)/\"\1\"/p" ips-$dc | paste -d, -s)
    cli=$(sed -n "$c p" bench_nodes-$dc)

    # we have seen some update_existing errors for the last key,
    # so we stop one key before just to avoid confusion
    [[ $tl_mode == lat ]] && tm=latest || tm=$tl_mode
    sed "s/\${ips}/$ips_str/
s/\${duration}/$dur/
s/\${num_keys}/$((TOTAL_KEYS-1))/
s/\${tl_mode}/$tm/
s/\${locality}/${loc[dc]}/
s/\${keygen}/$keygen/
s/\${operations}/$ops/" $CMB_HOME/bench.config > $conf_file.$cli

    scp -q $conf_file.$cli root@$cli:$BENCH_HOME/$conf_file &
  done
done; wait

update_conf_info tl_mode $tl_mode
update_conf_info popularity $pop
update_conf_info locality $locality
update_conf_info rw_ratio $rw_ratio

exit 0
