#!/bin/bash

in=(ev\|any\|lat locality popularity rw_ratio)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

[[ $1 == lat ]] && tl_mode=latest || tl_mode=any  # any for ev also
locality=$2
popularity=$3
rw_ratio=$4

case $popularity in
  uni) keygen=uniform_int;;
  par) keygen=truncated_pareto_int 
esac

gets=$(echo $rw_ratio | cut -d':' -f1)
upds=$(echo $rw_ratio | cut -d':' -f2)
ops=""
[[ $gets != 0 ]] && ops="{get, $gets}"
[[ $gets != 0 ]] && [[ $upds != 0 ]] && ops=$ops,
[[ $upds != 0 ]] && ops=$ops"{update_existing, $upds}"

clis=$(cat bench_nodes | wc -l)
((clis_dc=clis/2))
  
ips_dc=$(cat ips-1 | wc -l)  # both dcs have the same ip count
((ips_cli=ips_dc/clis_dc))
for dc in {1..2}; do
  [[ $dc -eq 1 ]] && loc=$locality || loc=$(bc <<< "1-$locality")
  loc=$(printf "%1.2f" $loc)

  for ((c=1, i=1; c<=clis_dc; c++, i+=ips_cli)); do
    ips_str=$(sed -n "$i,$((i+ips_cli-1)) s/\(.*\)/\"\1\"/p" ips-$dc | paste -d, -s)
    cli=$(sed -n "$c p" bench_nodes-$dc)

    # we have seen some update_existing errors for the last key,
    # so we stop one key before just to avoid confusion
    sed "s/\${ips}/$ips_str/
s/\${num_keys}/$((TOTAL_KEYS-1))/
s/\${tl_mode}/$tl_mode/
s/\${locality}/$loc/
s/\${keygen}/$keygen/
s/\${operations}/$ops/" $CMB_HOME/bench.config > bench.config.$cli

    scp bench.config.$cli root@$cli:$BENCH_HOME/bench.config
  done
done

update_conf_info tl_mode $tl_mode
update_conf_info popularity $popularity
update_conf_info locality $locality
update_conf_info rw_ratio $rw_ratio

exit 0
