#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR
rm -fr $TMP_DIR/*

outfile=$TMP_DIR/kadeploy.out

echo -n Waiting for job to be ready
while [[ -z $(jobid) ]]; do sleep 10; echo -n .; done && echo

create_all_nodes

echo "Deploying nodes"
#kadeploy3 -f all --multi-server -a $ENV_URL/$ENV_FILE -k $ENV_URL/authorized_keys > $outfile
kadeploy3 -a $ENV_FILE -f all_nodes -k > $outfile
[[ $? -ne 0 ]] && echo "Deployment failed" && exit 1

sed -n '/Nodes not correctly deployed/,$ s/\(.grid5000.fr*\).*/\1/p' kadeploy.out > $BLACKLIST
[[ -s $BLACKLIST ]] && echo "$(wc -l < $BLACKLIST) nodes not correctly deployed"

if [[ -n $(egrep "(ERROR|Cannot run the deployment)" $outfile || true) ]]; then
  echo -e "Deployment failed.\n $(cat $outfile)"
  exit 1
fi

echo "Deployment finished"
exit 0
