#!/bin/bash

in=(riak\|basho_bench)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

system=$1

for_all_p all_nodes "rsync -avz --delete --delete-excluded --exclude=app.config --exclude=vm.args $HOME/$system root@\$n:/opt"
