#!/bin/bash

set -ue
source $CMB_HOME/env.sh

[[ ! -e $RES_DIR ]] && echo "No results dir" && exit 0

cd $RES_DIR
for d in $(ls -r $RES_DIR); do
  if [[ ! -e $d/finished ]]; then
    echo "Removing unfinished: $d"
    rm -r $d
    continue
  else
    echo "Last finished: $d"
    params=""
    for k in tl_mode locality popularity rw_ratio delay; do
      v=$(get_prop $d/conf_info $k)
      if [[ $k == tl_mode ]]; then
        w=$(get_prop $d/conf_info w)
        [[ $(get_prop $d/conf_info consistency) == ev ]] && v=ev$w
      fi
      params=$params" "$v
    done
    echo "Last run:$params"
    break
  fi
done

exit 0
