#!/bin/bash

in=(ip [req_version])
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

req_version=${2:-latest}

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

ip=$(to_ip $1)

key=$(cat obj_keys | tr -d '\r')
curl -v http://$ip:8098$key?req_version=$req_version 2>&1 | sed 's/< X-Riak-Vclock: \(.*\)/\1/w obj_vclocks'
