#!/bin/bash

in=(host key [req_version])
[[ $# -lt 2 ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

host=$1
key=$2
req_version=${3:-latest}

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

curl -v http://$host:8098/riak/test/$key?req_version=$req_version 2>&1
