#!/bin/bash

option=${1:-"-lw"}

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

check_errors() {
  echo -e "\nErrors:"
  for n in $(cat srv_nodes); do
    errors=$(ssh root@$n "egrep -r \"\\[error\\]\" $RIAK_LOG_DIR || true")
    [[ -n $errors ]] && echo $errors && exit 1
  done
  echo # must echo/return something
}

if [[ $option == "-l" ]] || [[ $option == "-lw" ]]; then
  echo Loading
  for_all_p load_nodes "run_basho_bench \$n bench-load.config"
  check_errors
  echo "Loading finished"
fi

if [[ $option == "-w" ]] || [[ $option == "-lw" ]]; then
  if [[ $(get_prop conf_info consistency) == ev ]]; then
    echo "Skipping warm-up"
  else
    echo "Warming up"
    m0=$(riak_stats master_migrations_total)
    for i in $(seq 1 $((MIG_THOLD+1))); do
      for_all_p bench_nodes "run_basho_bench \$n bench-warmup.config"
      check_errors
    done
    m1=$(riak_stats master_migrations_total)
    echo "Warm-up finished ($((m1-m0)) migrations)"
  fi
fi

exit 0
