#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

$CMB_HOME/conf-load

echo Loading
for c in $(cat load_nodes); do
  run_basho_bench $c bench-load.config &
done; wait

echo -e "\n\nErrors:"
for n in $(cat srv_nodes); do
  ssh root@$n "egrep -r \"\\[error\\]\" $RIAK_LOG_DIR || true"
done

echo "Loading finished"
exit 0
