#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

cp $CMB_HOME/hosts hosts-1
cp $CMB_HOME/hosts hosts-2

site_gw=$(to_ip gw.$SITE.grid5000.fr)
for dc in {1..2}; do
  sn=("" $(subnets $dc 1-5))
  subnet=${sn[1]}
  broadcast=${sn[2]}
  netmask=${sn[3]}
  global_net=${sn[5]}

  for n in $(cat dc-$dc); do
    ip_g5k=$(to_ip $n)
    ip_sub=$(ip_in_subnet $subnet $ip_g5k)
    short=$(echo $n | cut -d'.' -f1)
    echo $ip_g5k >> ips-$dc
    echo -e "$ip_sub\t$n\t$short" >> hosts-$(other_dc $dc)

    ssh root@$n "
ifconfig $ETH:0 $ip_sub broadcast $broadcast netmask $netmask
route del -net $global_net netmask $netmask
route add -net $global_net netmask $netmask gw $site_gw dev $ETH:0" &
  done
done; wait

for dc in {1..2}; do
  for_all_p dc-$dc "scp -q hosts-$dc root@\$n:/etc/hosts"
done

exit 0
