#!/bin/bash

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

cp $CMB_HOME/hosts hosts-1
cp $CMB_HOME/hosts hosts-2

site_gw=$(to_ip gw.$SITE.grid5000.fr)
for dc in {1..2}; do
  for n in $(cat dc-$dc); do
    ip_g5k=$(to_ip $n)
    echo $ip_g5k >> ips-$dc

    subnet=$(subnets $dc 1)
    ip_sub=$(ip_in_subnet $subnet $ip_g5k)
    short=$(echo $n | cut -d'.' -f1)
    echo -e "$ip_sub\t$n\t$short" >> hosts-$(other_dc $dc)

    broadcast=$(subnets $dc 2)
    netmask=$(subnets $dc 3)
    global_net=$(subnets $dc 5)

    ssh root@$n "
ifconfig $ETH:0 $ip_sub broadcast $broadcast netmask $netmask
route del -net $global_net netmask $netmask
route add -net $global_net netmask $netmask gw $site_gw dev $ETH:0" &
  done
done
wait

for dc in {1..2}; do
  for n in $(cat dc-$dc); do
    scp hosts-$dc root@$n:/etc/hosts &
  done
done
wait

exit 0
