#!/bin/bash

req_version=${2:-latest}

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

key=$(cat obj_keys) # starts with a /
vclock=$(cat obj_vclocks)
content=$(date)

ip=$(to_ip $1)
curl -v -X PUT -d "$content" -H "Content-Type: text/plain" -H "X-Riak-Vclock: $vclock" http://$ip:8098$key?returnbody=true&req_version=$req_version 2>&1 | sed 's/< X-Riak-Vclock: \(.*\)/\1/w obj_vclocks'
