#!/bin/bash

in=(cluster nodes walltime +after_min\|when)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
source $CMB_HOME/env.sh

cluster=$1
nodes=$2
walltime=$3
when=$4
[[ $when == +* ]] && when=$(date -d "$when min" +"%Y-%m-%d %H:%M:%S")

oarsub -t deploy -t allow_classic_ssh -l slash_22=2+{"cluster='$cluster'"}nodes=$nodes,walltime=$walltime -r "$when"
outofchart -v

exit 0
