#!/bin/bash

in=(walltime nodes +after_min\|when)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -ue
source $CMB_HOME/env.sh

walltime=$1
nodes=$2
[[ $3 == +* ]] && when=$(date -d "$3 min" +"%Y-%m-%d %H:%M:%S") || when=$3

rm blacklist.conf; touch blacklist.conf

oarsub -t deploy -t allow_classic_ssh -l slash_22=2+{"cluster='$CLUSTER'"}nodes=$nodes,walltime=$walltime -r "$when"
echo "Crontab time: $(TZ="America/Sao_Paulo" date -d "$when GMT+2" +"%M %H %d %m *")"

exit 0
