#!/bin/bash

set -ue
source $CMB_HOME/env.sh
source $CMB_HOME/run-all-conf	# factor variables

done_log=$RES_DIR/exp_done.log

est_time() {
  local et=-
  if [[ $exec -gt 0 ]]; then
    local t1=$(date +%s)
    ((et=rem * (t1 - t0) / exec))
    # doesn't work for diffs > a day 
    et=$(date --date "1970-01-01 $et sec" +%T)
  fi
  echo $et
}

$CMB_HOME/srvs

((rem=${#ms[@]} * ${#ls[@]} * ${#ps[@]} * ${#rs[@]} * ${#ds[@]}))
echo "Number of tests: $rem"

prev=('' '' '' '' '' '')
started=false
exec=0
t0=$(date +%s)
for m in "${ms[@]}"; do
  for l in "${ls[@]}"; do
    for p in "${ps[@]}"; do
      for r in "${rs[@]}"; do
        for d in "${ds[@]}"; do
          for i in $(seq 1 $TESTS); do
            cur=($m $l $p $r $d $i)
            cur_str=$(echo ${cur[@]})
            if [[ -e $done_log ]] && \
               [[ -n $(grep "$cur_str" $done_log) ]]; then
              echo Skipping $cur_str
              prev=(${cur[@]})
              ((rem--)) || true
              continue
            else
              echo Running $cur_str
            fi

            [[ $m == ev1 ]] || [[ $m == ev2 ]] && c=ev || c=tl
            # if mode changed or is tl and loc / pop changed or not started yet
            if [[ $m != ${prev[0]} ]] || \
               [[ $c == tl && \
                "${cur[1]}${cur[2]}" != "${prev[1]}${prev[2]}" ]] || \
               [[ $started == false ]]; then
              echo "Starting / loading / warming up"
              $CMB_HOME/delay 0
              $CMB_HOME/riak $c
              $CMB_HOME/start	# includes stop
              $CMB_HOME/conf $m $l $p $r
              $CMB_HOME/load
              started=true
              sleep 15
            fi

            $CMB_HOME/delay $d
            $CMB_HOME/conf $m $l $p $r
            $CMB_HOME/run
            sleep 15

            ((exec++)) || true # when exec == 0, exit status == 1
            ((rem--)) || true
            echo ${cur[@]} >> $done_log
            prev=(${cur[@]})
            echo "Remaining: $rem / $(est_time)"
          done
        done
      done
    done
  done
done

$CMB_HOME/delay 0
$CMB_HOME/stop

echo run-all finished
