#!/bin/bash

set -ue

#modes=(ev1 ev2 any lat)
modes=(lat)
#locs=(0.5 0.9)
locs=(0.5)
pops=(uni)
#rws=(1:1 9:1)
rws=(1:1)

#delays=(0 50 100 150)
delays=(50)
delay_vars=(50)  # %
#losses=(0 0.05 1)
losses=(0.05)
dupls=(0)
corrupts=(0)
reorders=(0)
