#!/bin/bash

set -ue
source $CMB_HOME/env.sh
source $CMB_HOME/run-all-conf	# factor variables

done_log=$RES_DIR/exp_done.log

est_time() {
  local et=-
  if [[ $exec -gt 0 ]]; then
    local t1=$(date +%s)
    ((et=rem * (t1 - t0) / exec))
    # doesn't work for diffs > a day 
    et=$(date --date "1970-01-01 $et sec" +%T)
  fi
  echo $et
}

$CMB_HOME/srvs

((rem=${#modes[@]} * ${#locs[@]} * ${#pops[@]} * ${#rws[@]} * \
      ${#delays[@]} * ${#delay_vars[@]} * ${#delay_corrs[@]} * \
      ${#losses[@]} * ${#dupls[@]} * ${#corrupts[@]} * ${#reorders[@]} * \
      ${#reorder_corrs[@]} * ${#congests[@]}))
echo "Number of tests: $rem"

prev=('' '' '' '' '' '')
started=false
exec=0
t0=$(date +%s)
for mode in "${modes[@]}"; do
for loc in "${locs[@]}"; do
for pop in "${pops[@]}"; do
for rw in "${rws[@]}"; do
for delay in "${delays[@]}"; do
for delay_var in "${delay_vars[@]}"; do
for delay_corr in "${delay_corrs[@]}"; do
for loss in "${losses[@]}"; do
for dupl in "${dupls[@]}"; do
for corrupt in "${corrupts[@]}"; do
for reorder in "${reorders[@]}"; do
for reorder_corr in "${reorder_corrs[@]}"; do
for congest in "${congests[@]}"; do
for test in $(seq 1 $TESTS); do
  cur=($mode $loc $pop $rw $delay $delay_var $delay_corr $loss $dupl \
       $corrupt $reorder $reorder_corr $congest $test)
  cur_str=$(echo ${cur[@]})
  if [[ -e $done_log ]] && \
     [[ -n $(grep "$cur_str" $done_log) ]]; then
    echo Skipping $cur_str
    prev=(${cur[@]})
    ((rem--)) || true
    continue
  else
    echo Running $cur_str
  fi

  [[ $mode == ev1 ]] || [[ $mode == ev2 ]] && consist=ev || consist=tl
  # if mode changed or is tl and loc / pop changed or not started yet
  if [[ $mode != ${prev[0]} ]] || \
     [[ $consist == tl && "${cur[1]}${cur[2]}" != "${prev[1]}${prev[2]}" ]] || \
     [[ $started == false ]]; then
    echo "Starting / loading / warming up"
    $CMB_HOME/tune-tcp 0 cubic
    $CMB_HOME/wan 0 0 - 0 0 0 0 0
    $CMB_HOME/riak $consist
    $CMB_HOME/start	# includes stop
    $CMB_HOME/conf $mode $loc $pop $rw
    $CMB_HOME/load
    started=true
    sleep 15
  fi

  dv=$(bc -lq <<< "$delay*$delay_var/100" | xargs printf "%1.2f")
  $CMB_HOME/tune-tcp $delay $congest
  $CMB_HOME/wan $delay $dv $delay_corr $loss $dupl $corrupt \
                $reorder $reorder_corr
  $CMB_HOME/conf $mode $loc $pop $rw
  $CMB_HOME/run
  sleep 15

  ((exec++)) || true # when exec == 0, exit status == 1
  ((rem--)) || true
  echo ${cur[@]} >> $done_log
  prev=(${cur[@]})
  echo "Remaining: $rem / $(est_time)"
done
done
done
done
done
done
done
done
done
done
done
done
done
done

$CMB_HOME/tune-tcp 0 cubic
$CMB_HOME/wan 0 0 - 0 0 0 0 0
$CMB_HOME/stop

echo run-all finished
