#!/bin/bash

set -ue

modes=(ev1 ev2 any lat)
#modes=(lat)
locs=(0.5 0.9)
#locs=(0.5)
pops=(uni)
rws=(1:1)

delays=(0 50 100 150)
#delays=(50 150)
delay_vars=(0 60)  # %
#delay_vars=(1 60)  # %
losses=(0)
#losses=(0.01 0.3)
dupls=(0)
#dupls=(0.05 5)
corrupts=(0)
reorders=(0)
#reorders=(0.05 5)
