#!/bin/bash

in=(servers clients ev\|any\|lat rw_ratio delay)
[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1

set -u
source $CMB_HOME/env.sh
cd $CMB_HOME

servers=$1
clients=$2
consistency=$3
rw_ratio=$4
delay=$5

#[[ -e $TMP_DIR/srv_nodes_n ]] && ./conf-delay 0 && ./stop-cluster

set -e
echo ============
echo $consistency $rw_ratio $delay
echo ============
./conf-srvs $servers $clients $consistency $rw_ratio
./conf-delay $delay
./run-bench

exit 0
