#!/bin/bash

skip_cleaning=${1:-no}

set -ue
source $CMB_HOME/env.sh
cd $TMP_DIR

pongs=($(ssh_all_p srv_nodes "$RIAK_BIN_DIR/riak ping"))
for p in "${pongs[@]}"; do [[ $p == pong ]] && $CMB_HOME/stop && break; done

[[ $skip_cleaning != -s ]] && ssh_all_p srv_nodes "rm -fr $RIAK_DATA_DIR/*"

echo Starting
ssh_all_p srv_nodes "rm -fr $RIAK_LOG_DIR/*; $RIAK_BIN_DIR/riak start"

echo Joining
rn1=$(cat riak_nodes_1)
ssh_all srv_nodes_n "$RIAK_BIN_DIR/riak-admin join $rn1"

echo -n "Waiting for ring to be ready"
n1=$(cat srv_nodes_1)
srvs=$(cat srv_nodes | wc -l)
while [ $(ssh root@$n1 "$RIAK_BIN_DIR/riak-admin ringready" | wc -l) -ne $srvs ]; do
  echo -n .; sleep 3
done
echo

echo -n "Waiting for handoff to finish"
while [ $(ssh root@$n1 "$RIAK_BIN_DIR/riak-admin member_status" | awk '{ print $3 }' | sed -n "4,$((srvs+3)) p" | grep '\-\-' | wc -l) -ne $srvs ]; do
  echo -n .; sleep 10
done
echo

exit 0
