#!/bin/bash

set -u
source $CMB_HOME/env.sh
cd $TMP_DIR

echo Leaving
ssh_all_p srv_nodes_n "$RIAK_BIN_DIR/riak-admin leave"

echo Removing
n1=$(cat srv_nodes_1)
for n in $(cat riak_nodes_n); do
  ssh root@$n1 "$RIAK_BIN_DIR/riak-admin force-remove $n"
done

echo Stopping
ssh_all_p srv_nodes "$RIAK_BIN_DIR/riak stop"

exit 0
